language: java
jdk:
  - oraclejdk8

script:
  - unzip bin/lib.zip -d lambda-selenium-node/lib
  - unzip bin/node_modules.zip -d lambda-selenium-node/node_modules
  - zip -r node_lambda_function.zip lambda-selenium-node/*
  - cd lambda-selenium-java
  - gradle clean unzipLibs shadowJar
  - mv build/libs/lambda-selenium-all.jar ../java_lambda_function.zip
  - cd ../
  
deploy:
  provider: releases
  api_key: $github_token
  file:
    - "node_lambda_function.zip"
    - "java_lambda_function.zip"
  skip_cleanup: true
  on:
    tags: true
