language: java
jdk:
  - oraclejdk8

script:
  - unzip bin/lib.zip -d lambda-selenium-node/lib
  - unzip bin/node_modules.zip -d lambda-selenium-node/node_modules
  - zip -r node_lambda_function.zip lambda-selenium-node/*
  - unzip bin/lib.zip -d lambda-selenium-java/src/main/resources
  - cd lambda-selenium-java
  - gradle clean shadowJar
  - mv build/libs/lambda-selenium-all.jar ../java_lambda_function.zip
  
deploy:
  provider: releases
  api_key: $github_token
  file_glob: true
  file: "*_lambda_function.zip"
  skip_cleanup: true
  on:
    tags: true
